# ==== SCREEN SETTINGS ====
SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
BORDER = 10
FPS = 60

# ==== COLORS ====
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# ==== BALL SETTINGS ====
BALL_RADIUS = 10
BALL_SPEED_X = 4
BALL_SPEED_Y = 4
BALL_OFFSET = 1  # Distance from paddle when stationary

# ==== PADDLE SETTINGS ====
PADDLE_WIDTH, PADDLE_HEIGHT = 20, 80